config:
  node-pubsub:domain: dev.ozby.dev
  # Set these via: pulumi config set --secret <key> <value> --stack dev
  # node-pubsub:cloudflareAccountId: <your CF account ID>
  # node-pubsub:cloudflareZoneId: <CF zone ID for ozby.dev>

  node-pubsub:cloudflareAccountId:
    secure: AAABAP28N3NBJyiVGwf+rV/72rYuhalUxzBkArGtF+9LMPAHpvGORmzu2butm/iwZkzMUTN042pwBwwjaaMjyA==
  node-pubsub:cloudflareZoneId:
    secure: AAABAO8rYOyS1YEsro6Xo7+r/7rBAZ9Tno2suOUUM5fWBzFogHJlCA1zlmkzzabIN76oKtAVNi1vv9a7Nn5Dcw==
  node-pubsub:neonConnectionString:
    secure: AAABADCwaHySlnjEp0+qzLn8phD0EdOwc/bMtd1xOHTz39q5cWkzdzR3J+hCpX773cxcmUqAPZvxKDBqmBZvy/Qx81jyvX5BaOShGDme8Hm+Du2A/pA5itLjZzTsHIZGVSo6my4glYpVwdourzMd41yfFVb5+4Ihev30rZub/7l0txoBPyLwtsDCGg030dwpvxwXLFuZMy8iAbiaUYbasK6tGKeBBxJCn+qO00uPzAECsdoGGvtxGg==
