config:
  ingest-lens:domain: dev.ingest-lens.ozby.dev
  ingest-lens:cloudflareAccountId:
    secure: AAABAFh/kHvFCt5BrEXtd7Vmjgxgb/T6Xbm4INYhbFQzVWYt1edHm6vy1L1RJz9DDVdy8sihj88QI9jMtAYvDQ==
  ingest-lens:cloudflareZoneId:
    secure: AAABAFSUAH555sNmcG5NKKcm9JwkOBwb2p78OrNhIPTfg2rSCUS7oIBXDRVPaXhs1RFfQrxsHIYOw6m0ooIX2Q==
  ingest-lens:neonProjectId: lucky-king-24635750
  ingest-lens:neonRoleName: neondb_owner
  ingest-lens:neonRolePassword:
    secure: AAABAIyJbwqnfO8CVHuBvpA+0DPbwfTS6so/tZPEipeF7MGswUvZRMPAcnRhob3n
  ingest-lens:neonDatabaseName: neondb
  ingest-lens:neonParentBranchId: br-blue-brook-alwwzbdy
  ingest-lens:neonApiKey:
    secure: AAABAKtWVET1iSx/feV+RHSbtDI9ZatqFLM9o+NuXBwCDJY/SVfI6GaCCE0N+gt2z18op19GBizxClDQrusm36kN3o2dsytTPEY0Yt5MBqsU7n12bunL0amJkDS/0LZF/wo4Vtk=
  ingest-lens:neonConnectionString:
    secure: AAABAIpoEVr+opS4UwvLPseUvPmmt1pEM/F1UBC22sqduUa8YSRm1h6ghFPkfLzOi+ok2vA2mbum98ep56QWXkoyeoy1qiqlrOjCgda9BkleTryQ86FKBwFNWYQTyJw8j3EUHXFN9rqk6NPDeiTGMeE3G9jgjpjgz5l9O9gdvT2rLT1cKXQLuaDHGawWqmls4tKPkK8=
