name = "node-pubsub-vitest"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "TOPIC_ROOMS"
class_name = "TopicRoom"

[[durable_objects.bindings]]
name = "HEAL_STREAM"
class_name = "HealStreamDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TopicRoom", "HealStreamDO"]
