/**
 * Generates wrangler.toml binding overrides from Pulumi stack outputs.
 * Called by CI after `pulumi up` to inject live resource IDs.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import process from "node:process";

const stack = process.argv[2];
if (!stack) {
  console.error("Usage: bun ./src/deploy/wrangler-config.ts <stack>");
  process.exit(1);
}

const dopplerConfig = stack === "prd" ? "production" : "preview";
const doppler = `doppler run --project ozby-shell --config ${dopplerConfig} --`;

const outputs = JSON.parse(
  execSync(`${doppler} pulumi stack output --json --stack ${stack}`).toString(),
);

const toml = `
# AUTO-GENERATED by infra/src/deploy/wrangler-config.ts — do not edit by hand

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "${outputs.hyperdriveId}"

[[kv_namespaces]]
binding = "KV"
id = "${outputs.kvNamespaceId}"
`.trim();

writeFileSync("apps/workers/wrangler.generated.toml", toml);
console.log("wrangler.generated.toml written.");
